language: java

jdk:
  - oraclejdk8

notifications:
  email:
    on_failure: change # default: always

addons:
  sonarqube:

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

after_success:
  - bash <(curl -s https://codecov.io/bash)
